config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # resources :customers, only:[:index, :new, :create, :edit, :update] do
  #   resources :contracts, only:[:new, :create]
  # end
  # resources :contracts, only:[] do
  #   resources :insure_trad_supps, only:[:new, :create, :show]
  # end

  resources :customers, shallow: true, only:[:index, :new, :create, :edit, :update] do
    resources :contracts, shallow: true,  only:[:new, :create] do
      resources :insure_trad_supps, shallow: true, only:[:new, :create, :show] do
        resources :options, only:[:new, :create, :edit, :update]
        resources :customer_contacts, only:[:new, :create, :edit, :update]
        resources :customers_infos, only:[:new, :create, :edit, :update]
        resources :primary_insurances, only:[:new, :create, :edit, :update] do
          resources :loss_payees, only:[:new, :create, :edit, :update]
        end
      end
    end
  end
  get '/insure_trad_supps/:id/createpdf', to: 'insure_trad_supps#creationpdf', as: 'creation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :contracts
  validates :compagny_name, :address, :zip_code, :city, :country , :activity_code, :siret, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_compagny_name_and_siret,
    against: [ :compagny_name, :siret ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    # mettre un pgsearch ici
    @customers = Customer.all
    if params[:search].present?
      @customers = @customers.search_by_compagny_name_and_siret(params[:search])
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @contract = Contract.new
    if @customer.update(customer_params)
      redirect_to new_customer_contract_path(@customer, @contract)
    else
      render_error
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:compagny_name, :address, :zip_code, :city, :country, :activity_code, :siret)
  end

end

app/views/customers/edit.html.erb
<div class="container">
  <div class="title">
    <h2>INFORMATIONS ASSURÉ</h2>
    <p>Confirmez les informations obtenues sur
      votre assuré</p>
  </div>
  <%= simple_form_for(@customer) do |f| %>
  <div class="inline">
    <%= f.input :compagny_name %>
    <%= f.input :siret %>
  </div>
  <%= f.input :address %>
  <div class="inline">
    <%= f.input :zip_code %>
    <%= f.input :city %>
  </div>
  <%= f.input :country , as: :string%>
  <%= f.input :activity_code %>
  <p>
    Merci de modifier ou compléter les informations erronées ou manquantes
  </p>
  <%= f.submit 'Validez les informations' , class: 'btn btn-primary'  %>
  <%# probleme de boutton avec simple_form prend pas en compte la class peut etre change de simple avec tag par exemple ( cf index customers) %>
  <% end %>
</div>

app/views/customers/index.html.erb
<%
=begin%>
 commentaire : ici on peut faire creation nouveau client
<%
=end%>
<div class="container">
  <div class="title">
    <h2>L'ASSURÉ</h2>
    <p> Veuillez préciser le nom ou numéro siren de votre assuré</p>
  </div>
  <%= form_tag customers_path, method: :get do %>
  <%= text_field_tag :search,
      params[:search],
      class: "form-control",
      placeholder: "Find a compagny"
    %>
  <%= submit_tag "Search", class: "btn btn-primary my-2" %>
  <% end %>
  <% if (!(@customers == Customer.all)) %>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div id="customers">
        <% @customers.each do |customer| %>
        <%= link_to(edit_customer_path(customer)) do %>
        <div class='card'>
          <h4><%= customer.compagny_name %></h4>
          <p>Siren: <%= customer.siret %></p>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% else %>
  <% end %>
</div>