config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # resources :customers, only:[:index, :new, :create, :edit, :update] do
  #   resources :contracts, only:[:new, :create]
  # end
  # resources :contracts, only:[] do
  #   resources :insure_trad_supps, only:[:new, :create, :show]
  # end

  resources :customers, shallow: true, only:[:index, :new, :create, :edit, :update] do
    resources :contracts, shallow: true,  only:[:new, :create] do
      resources :insure_trad_supps, shallow: true, only:[:new, :create, :show] do
        resources :options, only:[:new, :create, :edit, :update]
        resources :customer_contacts, only:[:new, :create, :edit, :update]
        resources :customers_infos, only:[:new, :create, :edit, :update]
        resources :primary_insurances, only:[:new, :create, :edit, :update] do
          resources :loss_payees, only:[:new, :create, :edit, :update]
        end
      end
    end
  end
  get '/insure_trad_supps/:id/createpdf', to: 'insure_trad_supps#creationpdf', as: 'creation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/insure_trad_supp.rb
class InsureTradSupp < ApplicationRecord
  belongs_to :contract
  has_one :customer_contact
  has_one :customers_info
  has_one :primary_insurance
  has_one :option

  PERCENTS = [[0.1, 'moins de 10%'], [0.15, '11 % à 15 %'], [0.2, '16 % à 20 %'], [0.25, '20 % à 25 %'], [0.3, '26 % à 30 %'], [0, 'plus de  30 %']]
  CLIENTS =   [[20, 'moins de 25'], [35, '26 à 50'], [60, '51 à 75'], [85, '76 à 100'], [130, '101 à 150'], [185, '151 à 200'], [250, '200 à 300'], [400, 'plus de 301']]
  validates :amountCA, :percentBadlyCovert, :percentCA, :numberTotalInsured, presence: true
end

app/controllers/insure_trad_supps_controller.rb
class InsureTradSuppsController < ApplicationController
  def show
    @insure_trad_supp = InsureTradSupp.find(params[:id])
    if @insure_trad_supp.customers_info
      @customers_info = CustomersInfo.find(@insure_trad_supp.customers_info.id)
    else
      @customers_info = CustomersInfo.new
      @customers_info.insure_trad_supp = @insure_trad_supp
    end
    if @insure_trad_supp.customer_contact
      @customer_contact = CustomerContact.find(@insure_trad_supp.customer_contact.id)
    else
      @customer_contact = CustomerContact.new
      @customer_contact.insure_trad_supp = @insure_trad_supp
    end
    if @insure_trad_supp.primary_insurance
      @primary_insurance = PrimaryInsurance.find(@insure_trad_supp.primary_insurance.id)
    else
      @primary_insurance = PrimaryInsurance.new
      @primary_insurance.insure_trad_supp = @insure_trad_supp
    end
  end

  def new
    @contract = Contract.find(params[:contract_id])
    @insure_trad_supp = InsureTradSupp.new
  end

  def create
    @contract = Contract.find(params[:contract_id])
    @insure_trad_supp = InsureTradSupp.new(insure_trad_supp_params)
    @insure_trad_supp.contract = @contract
    if @insure_trad_supp.save
      redirect_to new_insure_trad_supp_option_path(@insure_trad_supp)
    else
      render :new
    end
  end

  def creationpdf
    @insure_trad_supp = InsureTradSupp.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Contrat",
        template: "insure_trad_supps/creationpdf.html.erb",
        layout: 'pdf.html',
        formats: :html, encoding: 'utf8'
      end
    end
end

  private

  def insure_trad_supp_params
    params.require(:insure_trad_supp).permit(:amountCA, :percentCA, :percentBadlyCovert, :numberTotalInsured)
  end
end

app/views/insure_trad_supps/creationpdf.html.erb
<div class="pdf">

  <div class="container">
    <h1 class="center">DISPOSITIONS CONTRACTUELLES DE VOTRE POLICE D'ASSURANCE CREDIT DE SECONDE LIGNE</h1>
    <p>Votre police d'assurance crédit de seconde ligne (la “Police”) est composée des éléments suivants :</p>
    <ul>
      <li>Les Conditions Générales « Trade Insure Seconde Ligne »</li>
      <li>Les Conditions Particulières</li>
      <li>Convention de Prestations de Services au titre de la police « Trade Insure Seconde Ligne »</li>
      <li>Le Devis que vous avez réalisé en ligne</li>
      <li>Mandat de Prélèvement au profit d’ Insure Trade Assurances</li>
      <li>Mandat de Prélèvement au profit d’ Insure Trade Servicing</li>
    </ul>
    <p>Les mots en italique se réfèrent à une valeur et sont expliqués dans les Conditions Particulières.</p>
    <p>Les termes en caractères gras sont définis à l’article 7 – Définitions</p>
    <h2>CONDITIONS PARTICULIÈRES</h2>
    <h3>Votre Intermédiaire d’assurance : ici mettre le courtier j'imagine</h3>
    <h3>Article 1. Vous/Assuré</h3>
    <table>
      <tbody>
        <tr>
          <td>Raison Sociale</td>
          <td><%= @insure_trad_supp.customers_info.compagny_name %></td>
        </tr>
        <tr>
          <td>Adresse</td>
          <td><%= @insure_trad_supp.contract.customer.address %></td>
        </tr>
        <tr>
          <td>Code Postale</td>
          <td><%= @insure_trad_supp.contract.customer.zip_code %>000</td>
        </tr>
        <tr>
          <td>Ville</td>
          <td><%= @insure_trad_supp.contract.customer.city %></td>
        </tr>
        <tr>
          <td>Pays</td>
          <td><%= @insure_trad_supp.contract.customer.country %></td>
        </tr>
        <tr>
          <td>N° Siren</td>
          <td><%= @insure_trad_supp.contract.customer.siret %></td>
        </tr>
        <tr>
          <td>Adresse de notification
            électronique</td>
          <td><%= @insure_trad_supp.customer_contact.email_correspondance %></td>
        </tr>
      </tbody>
    </table>
    <h3>Article 2 . Durée de la Police</h3>
    <p>La police entre en vigueur le <%= @insure_trad_supp.primary_insurance.policy_period_start %> et prendra fin le <%= @insure_trad_supp.primary_insurance.policy_period_end %>
      Vous bénéficiez d’un droit de renonciation à la mise en vigueur de cette police pendant un délai de
      quatorze jours (calendaires) jusqu’au <%= @insure_trad_supp.primary_insurance.policy_period_start.advance(days: 14) %> sans frais ni pénalité et vous renoncerez de ce fait
      à tous vos droits à indemnisation au titre de cette police de second rang. Passé cette date, la police
      est réputée être en vigueur et la prime pour le premier trimestre est due à InsureTrade Assurances.
      Cette police est annulée automatiquement et immédiatement dans tous ses effets en cas
      d’annulation, non mise en vigueur ou résiliation de votre police d’assurance-crédit de base en
      vigueur à la souscription de la présent police de second rang.
      Cette police est renouvelable par tacite reconduction. Toutefois, Vous pouvez résilier cette police à
      la fin de chaque période trimestrielle de chaque exercice annuel de la police moyennant un préavis
      de 15 jours après chaque date d’expiration trimestrielle et par Nous moyennant un préavis de 30
      jours avant chaque date d’expiration d’exercice annuel d’assurance.
    </p>
    <h3> Article 3 Nature des activités assurées : <%= @insure_trad_supp.customers_info.activity_code %></h3>
    <h3>Article 4 Description des produits/prestations de services assurés : <%= @insure_trad_supp.customers_info.saleInsured %></h3>

  </div>
</div>

app/views/insure_trad_supps/new.html.erb
<div class="avancement">
  <div class="position-avancement-actif inline-text">
    <div class="avancement-number">
      <p class=" actif-number">1</p>
    </div>
    <p>
      Choix de la <br>police
    </p>
  </div>
  <div class="position-avancement-a-faire inline-text">
    <div class="avancement-number">
      <p class=" a-faire-number">2</p>
    </div>
    <p>
      Tarification
    </p>
  </div>
  <div class="position-avancement-a-faire inline-text">
    <div class="avancement-number">
      <p class=" a-faire-number">3</p>
    </div>
    <p>
      Information <br>complémentaires
    </p>
  </div>
  <div class="position-avancement-a-faire inline-text">
    <div class="avancement-number">
      <p class=" a-faire-number">4</p>
    </div>
    <p>
      Création <br>police
    </p>
  </div>
</div>


<div class="container">
  <div class="title my-4">
    <h2>Police d'assurance de second rang</h2>
  </div>
  <%= simple_form_for [@contract, @insure_trad_supp] do |f| %>
  <p>Quel est le montant du chiffre d’affaires soumis à votre assureur crédit pour le dernier exercice annuel d’assurance?</p>
  <%= f.input :amountCA , label: false, input_html: { min: '0', step: '1000'} %>
  <p>Quel pourcentage de ce chiffre d’affaires est insuffisamment couvert?</p>
  <%= f.input :percentCA , label: false ,collection: InsureTradSupp::PERCENTS, label_method: :second, value_method: :first%>
  <p>Quel est le nombre total approximatif de vos clients actifs assurés?</p>
  <%= f.input :numberTotalInsured , label: false, collection: InsureTradSupp::CLIENTS, label_method: :second, value_method: :first%>
  <p>Quel est le pourcentage approximatif de ces clients actifs insuffisamment couverts?</p>
  <%= f.input :percentBadlyCovert , label: false, collection: InsureTradSupp::PERCENTS, label_method: :second, value_method: :first%>
  <%= f.submit 'Validez', class:'btn btn-primary' %>
  <% end %>
</div>

app/views/insure_trad_supps/show.html.erb
<div class="avancement">
  <div class="position-avancement-realise inline-text">
    <i class="fas fa-check-circle tick"></i>
    <p>
      Choix de la <br>police
    </p>
  </div>
  <div class="position-avancement-realise inline-text">
    <i class="fas fa-check-circle tick"></i>
    <p>
      Tarification
    </p>
  </div>
  <div class="position-avancement-a-faire inline-text">
    <div class="avancement-number">
      <p class=" actif-number">3</p>
    </div>
    <p>
      Information <br>complémentaires
    </p>
  </div>
  <div class="position-avancement-a-faire inline-text">
    <div class="avancement-number">
      <p class=" a-faire-number">4</p>
    </div>
    <p>
      Création <br>police
    </p>
  </div>
</div>

<div class="container ">
  <div class="title my-4">
    <h2>Informations complémentaires</h2>
    <p>Pour finaliser votre contrat nous avons besoin de ...</p>
  </div>
  <div id="police-second-rang" class="card-info">
    <div class="number">
      <% if @insure_trad_supp.customers_info.id == nil %>
      <p class="card-number card-number-active">1</p>
      <% else%>
      <p class="card-number card-number-inactive">1</p>
      <% end %>
    </div>
    <div class="card-content">
      <h3>Police de second rang</h3>
      <% if @insure_trad_supp.customers_info.id == nil %>
      <%= render 'customers_infos/new' %>
      <p><%= @insure_trad_supp.customers_info.id %></p>
      <% end %>
    </div>
    <% if @insure_trad_supp.customers_info.id != nil %>
    <div class="done">
      <i class="fas fa-check-circle tick green"></i>
    </div>
    <% end %>
  </div>
  <div id="contact" class="card-info">
    <div class="number">
      <% if @insure_trad_supp.customers_info.id != nil && @insure_trad_supp.customer_contact.id == nil%>
      <p class="card-number card-number-active">2</p>
      <% else %>
      <p class="card-number card-number-inactive">2</p>
      <% end %>
    </div>
    <div class="card-content">
      <h3>Contact chez l'assuré</h3>
      <% if @insure_trad_supp.customers_info.id != nil && @insure_trad_supp.customer_contact.id == nil%>
      <%= render 'customer_contacts/new' %>
      <% end %>
    </div>
    <% if @insure_trad_supp.customers_info.id != nil && @insure_trad_supp.customer_contact.id != nil%>
    <div class="done">
      <i class="fas fa-check-circle tick green"></i>
    </div>
    <% end %>
  </div>
  <div id="contact" class="card-info">
    <div class="number">
      <% if @insure_trad_supp.customers_info.id != nil && @insure_trad_supp.customer_contact.id != nil && @insure_trad_supp.primary_insurance.id == nil%>
      <p class="card-number card-number-active">3</p>
      <% else %>
      <p class="card-number card-number-inactive">3</p>
      <% end %>
    </div>
    <div class="card-content">
      <h3>Assureur crédit de base</h3>
      <% if @insure_trad_supp.customers_info.id != nil && @insure_trad_supp.customer_contact.id != nil && @insure_trad_supp.primary_insurance.id == nil%>
      <%= render 'primary_insurances/new' %>
      <% end %>
    </div>
    <% if @insure_trad_supp.customers_info.id != nil && @insure_trad_supp.customer_contact.id != nil && @insure_trad_supp.primary_insurance.id != nil%>
    <div class="done">
      <i class="fas fa-check-circle tick green"></i>
    </div>
    <% end %>
  </div>
  <div class="center">
    <%= link_to 'Telecharger la police', creation_path(@insure_trad_supp, :format => :pdf) , :class => "btn btn-success mt-4 button-contrat-creation-300" %>
  </div>
</div>